version: '3.8'

services:
    # Router
    router:
        build:
            context: .
            dockerfile: Dockerfile-RO
        container_name: visity-backend-router
        restart: unless-stopped
        tty: true
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        ports:
            - "80:80"
            - "443:443"
        networks:
            - visity-backend-network
    
    # Backend Service
    backend-app:
        build:
            context: .
            dockerfile: Dockerfile-BE
        container_name: visity-backend
        restart: unless-stopped
        tty: true
        networks:
            - visity-backend-network
             
    # Web Service
 #   web-app:
 #       build:
  #          context: .
 #           dockerfile: ./Dockerfile/Dockerfile-FE
  #      container_name: visity-backend-frontend
  #      restart: unless-stopped
  #      tty: true
  #      networks: 
  #          - visity-backend-network
    
    # Database Service
    mariadb:
        image: mariadb:latest
        container_name: visity-backend-database-mariadb
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: database_name
            MYSQL_USER: database_user
            MYSQL_PASSWORD: database_password
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        volumes:
            - visity-backend-data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks: 
            - visity-backend-network

# Docker Network
networks:
        visity-backend-network:
            driver: bridge

# Volumes
volumes:
        certbot-etc:
        certbot-var:
        visity-backend-data:
            driver: local
            
